import Test.KeyValueStoreExample.KeyValueStore
import Plausible.Arbitrary
import Plausible.DeriveArbitrary
import Plausible.Chamelean.ArbitrarySizedSuchThat
import Plausible.Chamelean.DeriveChecker
import Plausible.Chamelean.DeriveConstrainedProducer
import Plausible.Chamelean.EnumeratorCombinators
import Plausible.Chamelean.GeneratorCombinators

open Plausible
open KeyValueStore

-- Suppress warnings for unused variables in derived generators/checkers
set_option linter.unusedVariables false

-- Suppress warnings for redundant pattern-match cases in derived generators/checkers
set_option match.ignoreUnusedAlts true

/-- We override the default `Arbitrary` for `String`s so that we only produce strings of length 1
    where the string is a single letter from `A` to `I` -/
instance instKeyValueStoreArbitraryString : Arbitrary String where
  arbitrary := GeneratorCombinators.elementsWithDefault "A" ["A", "B", "C", "D", "E", "F", "G", "H", "I"]
#check String
-- instance (α : Type) y : ArbitrarySizedSuchThat α (fun x => Eq x y) where
--   arbitrarySizedST _ := return y

---------------------------------------------------------------------------------------------------------------------------------------
-- Derived Checkers & Generators (everything below in this file is automatically generated by Chamelean)
---------------------------------------------------------------------------------------------------------------------------------------

#guard_msgs(error, drop warning) in
#derive_generator (fun (s1 : List (String × String)) => KeyValueStore.RemoveKV k s1 s2)

#guard_msgs(error, drop warning) in
#derive_generator (fun (s2 : List (String × String)) => KeyValueStore.RemoveKV k s1 s2)


#guard_msgs(error, drop warning) in
#derive_generator (fun (s1 : List (String × String)) => KeyValueStore.AddKV k v s1 s2)

#guard_msgs(error, drop warning) in
#derive_generator (fun (s2 : List (String × String)) => KeyValueStore.AddKV k v s1 s2)

#guard_msgs(error, drop warning) in
#derive_generator (fun (v : String) => KeyValueStore.AddKV k v x_1 s2)

#guard_msgs(error, drop warning) in
#derive_checker (KeyValueStore.LookupKV s kv)

#guard_msgs(error, drop warning) in
#derive_generator (fun (s1 : List (String × String)) => KeyValueStore.LookupKV s1 kv)

#guard_msgs(error, drop warning) in
#derive_checker (KeyValueStore.AddKV k2 v s_1 s2)

#guard_msgs(error, drop warning) in
#derive_checker (KeyValueStore.RemoveKV k s_1 s2)

#guard_msgs(error, drop warning) in
#derive_generator (fun (s : List (String × String)) => KeyValueStore.EvalStateApiCall s x)

#guard_msgs(error, drop warning) in
#derive_generator (fun (kv : StateResult × String × Nat × String) => KeyValueStore.LookupKV s kv)

#guard_msgs(error, drop warning) in
#derive_checker (KeyValueStore.GetBucket a b)

#guard_msgs(error, drop warning) in
#derive_generator (fun (nb : Nat × List (String × String)) => KeyValueStore.GetBucket s nb)

set_option diagnostics true
-- instance :
    ArbitrarySizedSuchThat (StateAPICall × StateResult × List (String × String))
      (fun foo_1 => KeyValueStore.EvalStateApiCall x_1 foo_1)
    where
  arbitrarySizedST :=
    let rec aux_arb (initSize : Nat) (size : Nat) (x_1 : List (String × String)) :
      OptionT Plausible.Gen (StateAPICall × StateResult × List (String × String)) :=
      (match size with
      | Nat.zero =>
        OptionTGen.backtrack
          [(1, do
              let k ← OptionT.lift Plausible.Arbitrary.arbitrary;
              do
                let v ← OptionT.lift Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    pure $
                      Prod.mk (KeyValueStore.StateAPICall.Get k (Option.none))
                        (Prod.mk (KeyValueStore.StateResult.Result v) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    pure $
                      Prod.mk (KeyValueStore.StateAPICall.Get k (Option.none))
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let n ← Plausible.Arbitrary.arbitrary;
                do
                  let v ← Plausible.Arbitrary.arbitrary;
                  match
                      DecOpt.decOpt
                        (KeyValueStore.LookupKV x_1 (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk n v))))
                        initSize with
                    | Option.some Bool.true =>
                      pure $
                        Prod.mk (KeyValueStore.StateAPICall.Get k (Option.some n))
                          (Prod.mk (KeyValueStore.StateResult.Result v) x_1)
                    | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let n ← Plausible.Arbitrary.arbitrary;
                do
                  let v ← Plausible.Arbitrary.arbitrary;
                  match
                      DecOpt.decOpt
                        (KeyValueStore.LookupKV x_1
                          (Prod.mk (KeyValueStore.StateResult.NoSuchVersionFailure) (Prod.mk k (Prod.mk n v))))
                        initSize with
                    | Option.some Bool.true =>
                      pure $
                        Prod.mk (KeyValueStore.StateAPICall.Get k (Option.some n))
                          (Prod.mk (KeyValueStore.StateResult.NoSuchVersionFailure) x_1)
                    | _ => OptionT.fail),
            (1, do
              let k ← OptionT.lift Plausible.Arbitrary.arbitrary;
              do
                let v ← OptionT.lift Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    return Prod.mk (KeyValueStore.StateAPICall.KeyExists k) (Prod.mk (KeyValueStore.StateResult.Ok) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← OptionT.lift Plausible.Arbitrary.arbitrary;
              do
                let v ← OptionT.lift Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    pure $
                      Prod.mk (KeyValueStore.StateAPICall.KeyExists k)
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyResult) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                do
                  let s2 ← ArbitrarySizedSuchThat.arbitrarySizedST (fun s2 => KeyValueStore.AddKV k v x_1 s2) initSize;
                  return Prod.mk (KeyValueStore.StateAPICall.Set k v) (Prod.mk (KeyValueStore.StateResult.Ok) s2)),
            (1, do
              let k2 ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                do
                  let s2 ← ArbitrarySizedSuchThat.arbitrarySizedST (fun s2 => KeyValueStore.AddKV k2 v x_1 s2) initSize;
                  do
                    let k ← Plausible.Arbitrary.arbitrary;
                    match
                        DecOpt.decOpt
                          (KeyValueStore.LookupKV x_1
                            (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                          initSize with
                      | Option.some Bool.true =>
                        pure $
                          Prod.mk (KeyValueStore.StateAPICall.Copy k k2) (Prod.mk (KeyValueStore.StateResult.Ok) s2)
                      | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true => do
                    let k2 ← Plausible.Arbitrary.arbitrary;
                    pure $
                        Prod.mk (KeyValueStore.StateAPICall.Copy k k2)
                          (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) x_1)
                  | _ => OptionT.fail),
            (1, do
              let v ← Plausible.Arbitrary.arbitrary;
              do
                let v2 ← Plausible.Arbitrary.arbitrary;
                do
                  let v3 := v ++ v2;
                  do
                    let k ← Plausible.Arbitrary.arbitrary;
                    match
                        DecOpt.decOpt
                          (KeyValueStore.LookupKV x_1
                            (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                          initSize with
                      | Option.some Bool.true => do
                        let s2 ←
                          ArbitrarySizedSuchThat.arbitrarySizedST (fun s2 => KeyValueStore.AddKV k v3 x_1 s2) initSize;
                        pure $
                            Prod.mk (KeyValueStore.StateAPICall.Append k v3) (Prod.mk (KeyValueStore.StateResult.Ok) s2)
                      | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true => do
                    let v2 ← Plausible.Arbitrary.arbitrary;
                    pure $
                        Prod.mk (KeyValueStore.StateAPICall.Append k v2)
                          (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let s2 ← ArbitrarySizedSuchThat.arbitrarySizedST (fun s2 => KeyValueStore.RemoveKV k x_1 s2) initSize;
                do
                  let v ← Plausible.Arbitrary.arbitrary;
                  match
                      DecOpt.decOpt
                        (KeyValueStore.LookupKV x_1
                          (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                        initSize with
                    | Option.some Bool.true =>
                      return Prod.mk (KeyValueStore.StateAPICall.Delete k) (Prod.mk (KeyValueStore.StateResult.Ok) s2)
                    | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    pure $
                      Prod.mk (KeyValueStore.StateAPICall.Delete k)
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) x_1)
                  | _ => OptionT.fail)]
      | Nat.succ size' =>
        OptionTGen.backtrack
          [(1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    pure $
                      Prod.mk (KeyValueStore.StateAPICall.Get k (Option.none))
                        (Prod.mk (KeyValueStore.StateResult.Result v) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    pure $
                      Prod.mk (KeyValueStore.StateAPICall.Get k (Option.none))
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let n ← Plausible.Arbitrary.arbitrary;
                do
                  let v ← Plausible.Arbitrary.arbitrary;
                  match
                      DecOpt.decOpt
                        (KeyValueStore.LookupKV x_1 (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk n v))))
                        initSize with
                    | Option.some Bool.true =>
                      pure $
                        Prod.mk (KeyValueStore.StateAPICall.Get k (Option.some n))
                          (Prod.mk (KeyValueStore.StateResult.Result v) x_1)
                    | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let n ← Plausible.Arbitrary.arbitrary;
                do
                  let v ← Plausible.Arbitrary.arbitrary;
                  match
                      DecOpt.decOpt
                        (KeyValueStore.LookupKV x_1
                          (Prod.mk (KeyValueStore.StateResult.NoSuchVersionFailure) (Prod.mk k (Prod.mk n v))))
                        initSize with
                    | Option.some Bool.true =>
                      pure $
                        Prod.mk (KeyValueStore.StateAPICall.Get k (Option.some n))
                          (Prod.mk (KeyValueStore.StateResult.NoSuchVersionFailure) x_1)
                    | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    return Prod.mk (KeyValueStore.StateAPICall.KeyExists k) (Prod.mk (KeyValueStore.StateResult.Ok) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    pure $
                      Prod.mk (KeyValueStore.StateAPICall.KeyExists k)
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyResult) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                do
                  let s2 ← ArbitrarySizedSuchThat.arbitrarySizedST (fun s2 => KeyValueStore.AddKV k v x_1 s2) initSize;
                  return Prod.mk (KeyValueStore.StateAPICall.Set k v) (Prod.mk (KeyValueStore.StateResult.Ok) s2)),
            (1, do
              let k2 ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                do
                  let s2 ← ArbitrarySizedSuchThat.arbitrarySizedST (fun s2 => KeyValueStore.AddKV k2 v x_1 s2) initSize;
                  do
                    let k ← Plausible.Arbitrary.arbitrary;
                    match
                        DecOpt.decOpt
                          (KeyValueStore.LookupKV x_1
                            (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                          initSize with
                      | Option.some Bool.true =>
                        pure $
                          Prod.mk (KeyValueStore.StateAPICall.Copy k k2) (Prod.mk (KeyValueStore.StateResult.Ok) s2)
                      | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true => do
                    let k2 ← Plausible.Arbitrary.arbitrary;
                    pure $
                        Prod.mk (KeyValueStore.StateAPICall.Copy k k2)
                          (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) x_1)
                  | _ => OptionT.fail),
            (1, do
              let v ← Plausible.Arbitrary.arbitrary;
              do
                let v2 ← Plausible.Arbitrary.arbitrary;
                do
                  let v3 := v ++ v2;
                  do
                    let k ← Plausible.Arbitrary.arbitrary;
                    match
                        DecOpt.decOpt
                          (KeyValueStore.LookupKV x_1
                            (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                          initSize with
                      | Option.some Bool.true => do
                        let s2 ←
                          ArbitrarySizedSuchThat.arbitrarySizedST (fun s2 => KeyValueStore.AddKV k v3 x_1 s2) initSize;
                        pure $
                            Prod.mk (KeyValueStore.StateAPICall.Append k v3) (Prod.mk (KeyValueStore.StateResult.Ok) s2)
                      | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true => do
                    let v2 ← Plausible.Arbitrary.arbitrary;
                    pure $
                        Prod.mk (KeyValueStore.StateAPICall.Append k v2)
                          (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let s2 ← ArbitrarySizedSuchThat.arbitrarySizedST (fun s2 => KeyValueStore.RemoveKV k x_1 s2) initSize;
                do
                  let v ← Plausible.Arbitrary.arbitrary;
                  match
                      DecOpt.decOpt
                        (KeyValueStore.LookupKV x_1
                          (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                        initSize with
                    | Option.some Bool.true =>
                      return Prod.mk (KeyValueStore.StateAPICall.Delete k) (Prod.mk (KeyValueStore.StateResult.Ok) s2)
                    | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    pure $
                      Prod.mk (KeyValueStore.StateAPICall.Delete k)
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) x_1)
                  | _ => OptionT.fail),
            ])
    fun size => aux_arb size size x_1

instance :
    ArbitrarySizedSuchThat (StateAPICall × StateResult × List (String × String))
      (fun foo_1 => KeyValueStore.EvalStateApiCall x_1 foo_1)
    where
  arbitrarySizedST :=
    let rec aux_arb (initSize : Nat) (size : Nat) (x_1 : List (String × String)) :
      OptionT Plausible.Gen (StateAPICall × StateResult × List (String × String)) :=
      (match size with
      | Nat.zero =>
        OptionTGen.backtrack
          [(1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    pure $                       Prod.mk (KeyValueStore.StateAPICall.Get k (Option.none))
                        (Prod.mk (KeyValueStore.StateResult.Result v) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    pure $                       Prod.mk (KeyValueStore.StateAPICall.Get k (Option.none))
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let n ← Plausible.Arbitrary.arbitrary;
                do
                  let v ← Plausible.Arbitrary.arbitrary;
                  match
                      DecOpt.decOpt
                        (KeyValueStore.LookupKV x_1 (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk n v))))
                        initSize with
                    | Option.some Bool.true =>
                      pure $                         Prod.mk (KeyValueStore.StateAPICall.Get k (Option.some n))
                          (Prod.mk (KeyValueStore.StateResult.Result v) x_1)
                    | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let n ← Plausible.Arbitrary.arbitrary;
                do
                  let v ← Plausible.Arbitrary.arbitrary;
                  match
                      DecOpt.decOpt
                        (KeyValueStore.LookupKV x_1
                          (Prod.mk (KeyValueStore.StateResult.NoSuchVersionFailure) (Prod.mk k (Prod.mk n v))))
                        initSize with
                    | Option.some Bool.true =>
                      pure $                         Prod.mk (KeyValueStore.StateAPICall.Get k (Option.some n))
                          (Prod.mk (KeyValueStore.StateResult.NoSuchVersionFailure) x_1)
                    | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    return Prod.mk (KeyValueStore.StateAPICall.KeyExists k) (Prod.mk (KeyValueStore.StateResult.Ok) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    pure $                       Prod.mk (KeyValueStore.StateAPICall.KeyExists k)
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyResult) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                do
                  let s2 ← ArbitrarySizedSuchThat.arbitrarySizedST (fun s2 => KeyValueStore.AddKV k v x_1 s2) initSize;
                  return Prod.mk (KeyValueStore.StateAPICall.Set k v) (Prod.mk (KeyValueStore.StateResult.Ok) s2)),
            (1, do
              let k2 ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                do
                  let s2 ← ArbitrarySizedSuchThat.arbitrarySizedST (fun s2 => KeyValueStore.AddKV k2 v x_1 s2) initSize;
                  do
                    let k ← Plausible.Arbitrary.arbitrary;
                    match
                        DecOpt.decOpt
                          (KeyValueStore.LookupKV x_1
                            (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                          initSize with
                      | Option.some Bool.true =>
                        pure $                           Prod.mk (KeyValueStore.StateAPICall.Copy k k2) (Prod.mk (KeyValueStore.StateResult.Ok) s2)
                      | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true => do
                    let k2 ← Plausible.Arbitrary.arbitrary;
                    pure $                         Prod.mk (KeyValueStore.StateAPICall.Copy k k2)
                          (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) x_1)
                  | _ => OptionT.fail),
            (1, do
              let v ← Plausible.Arbitrary.arbitrary;
              do
                let v2 ← Plausible.Arbitrary.arbitrary;
                do
                  let v3 ← ArbitrarySizedSuchThat.arbitrarySizedST (fun v3 => Eq v3 (v ++ v2)) initSize;
                  do
                    let k ← Plausible.Arbitrary.arbitrary;
                    match
                        DecOpt.decOpt
                          (KeyValueStore.LookupKV x_1
                            (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                          initSize with
                      | Option.some Bool.true => do
                        let s2 ←
                          ArbitrarySizedSuchThat.arbitrarySizedST (fun s2 => KeyValueStore.AddKV k v3 x_1 s2) initSize;
                        pure $                             Prod.mk (KeyValueStore.StateAPICall.Append k v3) (Prod.mk (KeyValueStore.StateResult.Ok) s2)
                      | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true => do
                    let v2 ← Plausible.Arbitrary.arbitrary;
                    pure $                         Prod.mk (KeyValueStore.StateAPICall.Append k v2)
                          (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let s2 ← ArbitrarySizedSuchThat.arbitrarySizedST (fun s2 => KeyValueStore.RemoveKV k x_1 s2) initSize;
                do
                  let v ← Plausible.Arbitrary.arbitrary;
                  match
                      DecOpt.decOpt
                        (KeyValueStore.LookupKV x_1
                          (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                        initSize with
                    | Option.some Bool.true =>
                      return Prod.mk (KeyValueStore.StateAPICall.Delete k) (Prod.mk (KeyValueStore.StateResult.Ok) s2)
                    | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    pure $                       Prod.mk (KeyValueStore.StateAPICall.Delete k)
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) x_1)
                  | _ => OptionT.fail)]
      | Nat.succ size' =>
        OptionTGen.backtrack
          [(1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    pure $                       Prod.mk (KeyValueStore.StateAPICall.Get k (Option.none))
                        (Prod.mk (KeyValueStore.StateResult.Result v) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    pure $                       Prod.mk (KeyValueStore.StateAPICall.Get k (Option.none))
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let n ← Plausible.Arbitrary.arbitrary;
                do
                  let v ← Plausible.Arbitrary.arbitrary;
                  match
                      DecOpt.decOpt
                        (KeyValueStore.LookupKV x_1 (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk n v))))
                        initSize with
                    | Option.some Bool.true =>
                      pure $                         Prod.mk (KeyValueStore.StateAPICall.Get k (Option.some n))
                          (Prod.mk (KeyValueStore.StateResult.Result v) x_1)
                    | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let n ← Plausible.Arbitrary.arbitrary;
                do
                  let v ← Plausible.Arbitrary.arbitrary;
                  match
                      DecOpt.decOpt
                        (KeyValueStore.LookupKV x_1
                          (Prod.mk (KeyValueStore.StateResult.NoSuchVersionFailure) (Prod.mk k (Prod.mk n v))))
                        initSize with
                    | Option.some Bool.true =>
                      pure $                         Prod.mk (KeyValueStore.StateAPICall.Get k (Option.some n))
                          (Prod.mk (KeyValueStore.StateResult.NoSuchVersionFailure) x_1)
                    | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    return Prod.mk (KeyValueStore.StateAPICall.KeyExists k) (Prod.mk (KeyValueStore.StateResult.Ok) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    pure $                       Prod.mk (KeyValueStore.StateAPICall.KeyExists k)
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyResult) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                do
                  let s2 ← ArbitrarySizedSuchThat.arbitrarySizedST (fun s2 => KeyValueStore.AddKV k v x_1 s2) initSize;
                  return Prod.mk (KeyValueStore.StateAPICall.Set k v) (Prod.mk (KeyValueStore.StateResult.Ok) s2)),
            (1, do
              let k2 ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                do
                  let s2 ← ArbitrarySizedSuchThat.arbitrarySizedST (fun s2 => KeyValueStore.AddKV k2 v x_1 s2) initSize;
                  do
                    let k ← Plausible.Arbitrary.arbitrary;
                    match
                        DecOpt.decOpt
                          (KeyValueStore.LookupKV x_1
                            (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                          initSize with
                      | Option.some Bool.true =>
                        pure $                           Prod.mk (KeyValueStore.StateAPICall.Copy k k2) (Prod.mk (KeyValueStore.StateResult.Ok) s2)
                      | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true => do
                    let k2 ← Plausible.Arbitrary.arbitrary;
                    pure $                         Prod.mk (KeyValueStore.StateAPICall.Copy k k2)
                          (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) x_1)
                  | _ => OptionT.fail),
            (1, do
              let v ← Plausible.Arbitrary.arbitrary;
              do
                let (v2 : String) ← Plausible.Arbitrary.arbitrary;
                do
                  let v3 ← ArbitrarySizedSuchThat.arbitrarySizedST (fun v3 => Eq v3 (HAppend.hAppend v v2)) initSize;
                  do
                    let k ← Plausible.Arbitrary.arbitrary;
                    match
                        DecOpt.decOpt
                          (KeyValueStore.LookupKV x_1
                            (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                          initSize with
                      | Option.some Bool.true => do
                        let s2 ←
                          ArbitrarySizedSuchThat.arbitrarySizedST (fun s2 => KeyValueStore.AddKV k v3 x_1 s2) initSize;
                        pure $                             Prod.mk (KeyValueStore.StateAPICall.Append k v3) (Prod.mk (KeyValueStore.StateResult.Ok) s2)
                      | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true => do
                    let v2 ← Plausible.Arbitrary.arbitrary;
                    pure $                         Prod.mk (KeyValueStore.StateAPICall.Append k v2)
                          (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) x_1)
                  | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let s2 ← ArbitrarySizedSuchThat.arbitrarySizedST (fun s2 => KeyValueStore.RemoveKV k x_1 s2) initSize;
                do
                  let v ← Plausible.Arbitrary.arbitrary;
                  match
                      DecOpt.decOpt
                        (KeyValueStore.LookupKV x_1
                          (Prod.mk (KeyValueStore.StateResult.Ok) (Prod.mk k (Prod.mk (Nat.zero) v))))
                        initSize with
                    | Option.some Bool.true =>
                      return Prod.mk (KeyValueStore.StateAPICall.Delete k) (Prod.mk (KeyValueStore.StateResult.Ok) s2)
                    | _ => OptionT.fail),
            (1, do
              let k ← Plausible.Arbitrary.arbitrary;
              do
                let v ← Plausible.Arbitrary.arbitrary;
                match
                    DecOpt.decOpt
                      (KeyValueStore.LookupKV x_1
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) (Prod.mk k (Prod.mk (Nat.zero) v))))
                      initSize with
                  | Option.some Bool.true =>
                    pure $                       Prod.mk (KeyValueStore.StateAPICall.Delete k)
                        (Prod.mk (KeyValueStore.StateResult.NoSuchKeyFailure) x_1)
                  | _ => OptionT.fail),
            ])
    fun size => aux_arb size size x_1
#check (fun x y => x ++ y)
def genUsesEq y z := do
  let a ← ArbitrarySizedSuchThat.arbitrarySizedST (fun x => x = y ++ z) 1
  return a

#eval OptionTGen.runSizedGenPrintOutput (fun _ => genUsesEq) 1

#derive_generator (fun (foo : StateAPICall × StateResult × List (String × String)) => KeyValueStore.EvalStateApiCall x foo)

#guard_msgs(error, drop warning) in
#derive_generator (fun (crns : APICall × Result × (Nat × List (Nat × List (String × String)))) => KeyValueStore.EvalApiCall s crns)

#derive_generator (fun (s : _) => KeyValueStore.GetBucket s nx)

#derive_generator (fun (s2_1 : _) => KeyValueStore.EvalApiCall s2_1 c)

#derive_enumerator (fun (s : _) => KeyValueStore.GetBucket s n)

#derive_enumerator (fun (x_1 : _) => KeyValueStore.AddKV k v x_1 s2)

#derive_enumerator (fun (x_1 : _) => KeyValueStore.LookupKV x_1 s)

#derive_enumerator (fun (x : _) => KeyValueStore.EvalStateApiCall x (c, r, x'))

#derive_checker (KeyValueStore.EvalApiCall s2_1 c)

#derive_generator (fun (s2 : _) => KeyValueStore.EvalApiCalls s2 (crs, s3))

#guard_msgs(error, drop warning) in
#derive_generator (fun (o : List (APICall × Result) × (Nat × List (Nat × List (String × String)))) => KeyValueStore.EvalApiCalls s o)


/- Uncommenting the following line results in random sequences of API Calls, such as:

```lean
 ([(APICall.CreateBucket, Result.Created 0),
  (APICall.OpBucket 0 (StateAPICall.Delete "B"),
   Result.OpResult (StateResult.NoSuchKeyFailure)),
  (APICall.CreateBucket, Result.Created 1),
  (APICall.DeleteBucket 0, Result.Removed),
  (APICall.CreateBucket, Result.Created 2),
  (APICall.CreateBucket, Result.Created 3),
  (APICall.DeleteBucket 1, Result.Removed),
  (APICall.CreateBucket, Result.Created 4),
  (APICall.DeleteBucket 2, Result.Removed),
  (APICall.OpBucket 3 (StateAPICall.Get "E" none),
   Result.OpResult (StateResult.NoSuchKeyFailure)),
  (APICall.CreateBucket, Result.Created 5),
  (APICall.OpBucket 3 (StateAPICall.Append "B" "D"),
   Result.OpResult (StateResult.NoSuchKeyFailure)),
  (APICall.DeleteBucket 3, Result.Removed),
  (APICall.CreateBucket, Result.Created 6)],
 7,
 [(6, []), (5, []), (4, [])])
```

-/
-- #eval OptionTGen.runSizedGen (ArbitrarySizedSuchThat.arbitrarySizedST (fun crs => KeyValueStore.EvalApiCalls (0, []) crs)) 1
