import Test.KeyValueStoreExample.KeyValueStore
import Plausible.Arbitrary
import Plausible.DeriveArbitrary
import Plausible.Chamelean.ArbitrarySizedSuchThat
import Plausible.Chamelean.DeriveChecker
import Plausible.Chamelean.DeriveConstrainedProducer
import Plausible.Chamelean.EnumeratorCombinators
import Plausible.Chamelean.GeneratorCombinators

open Plausible
open KeyValueStore

-- Suppress warnings for unused variables in derived generators/checkers
set_option linter.unusedVariables false

-- Suppress warnings for redundant pattern-match cases in derived generators/checkers
set_option match.ignoreUnusedAlts true

/-- We override the default `Arbitrary` for `String`s so that we only produce strings of length 1
    where the string is a single letter from `A` to `I` -/
instance instKeyValueStoreArbitraryString : Arbitrary String where
  arbitrary := GeneratorCombinators.elementsWithDefault "A" ["A", "B", "C", "D", "E", "F", "G", "H", "I"]
#check String
-- instance (α : Type) y : ArbitrarySizedSuchThat α (fun x => Eq x y) where
--   arbitrarySizedST _ := return y

---------------------------------------------------------------------------------------------------------------------------------------
-- Derived Checkers & Generators (everything below in this file is automatically generated by Chamelean)
---------------------------------------------------------------------------------------------------------------------------------------

def e := by_elab (do Lean.Elab.Term.elabType (← constructorExprToTSyntaxTerm (.Ctor `List [.Ctor `Prod [.Ctor `String [], .Ctor `String []]])))

def et : e := [("","")]

#print et

#eval (constructorExprToTSyntaxTerm (.Ctor `List [.Ctor `Prod [.Ctor `String [], .Ctor `String []]]))

#print e

#derive_generator (fun (vk_v : _) => KeyValueStore.LookupKV x_1 vk_v)

#derive_generator (fun (s2 : List (Prod String String)) => KeyValueStore.RemoveKV k x_1 s2)

#derive_generator (fun (s2 : List (Prod String String)) => KeyValueStore.AddKV k v x_1 s2)

#derive_generator (fun (k2 : String) => KeyValueStore.AddKV k2 v x_1 s2)

#derive_generator (fun (vc_r_x' : _) => KeyValueStore.EvalStateApiCall x vc_r_x')

#derive_generator (fun (vn'_x : _) => KeyValueStore.GetBucket s vn'_x)

#derive_generator (fun (vc_r_s2 : _) => KeyValueStore.EvalApiCall s_1 vc_r_s2)

#guard_msgs(error, drop warning) in
#derive_generator (fun (o : List (APICall × Result) × (Nat × List (Nat × List (String × String)))) => KeyValueStore.EvalApiCalls s o)


/- Uncommenting the following line results in random sequences of API Calls, such as:

```lean
 ([(APICall.CreateBucket, Result.Created 0),
  (APICall.OpBucket 0 (StateAPICall.Delete "B"),
   Result.OpResult (StateResult.NoSuchKeyFailure)),
  (APICall.CreateBucket, Result.Created 1),
  (APICall.DeleteBucket 0, Result.Removed),
  (APICall.CreateBucket, Result.Created 2),
  (APICall.CreateBucket, Result.Created 3),
  (APICall.DeleteBucket 1, Result.Removed),
  (APICall.CreateBucket, Result.Created 4),
  (APICall.DeleteBucket 2, Result.Removed),
  (APICall.OpBucket 3 (StateAPICall.Get "E" none),
   Result.OpResult (StateResult.NoSuchKeyFailure)),
  (APICall.CreateBucket, Result.Created 5),
  (APICall.OpBucket 3 (StateAPICall.Append "B" "D"),
   Result.OpResult (StateResult.NoSuchKeyFailure)),
  (APICall.DeleteBucket 3, Result.Removed),
  (APICall.CreateBucket, Result.Created 6)],
 7,
 [(6, []), (5, []), (4, [])])
```

-/

#guard_msgs(drop info) in
#eval OptionTGen.runSizedGenPrintOutput (ArbitrarySizedSuchThat.arbitrarySizedST (fun crs => KeyValueStore.EvalApiCalls (0, []) crs)) 3
